services:
  db:
    container_name: alugaMeDB
    image: postgres:17
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=alugaMeDB
    ports:
      - "5432:5432"
